@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NzExNTgxOTh9.hiEXwBMhq3pHEToUPX3cUKh_Uxk37iGS_KzDdWY1Jo4

### Product Index Action

GET http://localhost:3000/products.json?category


#--------------------------------------------------
### Product Show Action

GET http://localhost:3000/products/3.json


#--------------------------------------------------
### Product Create

POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Lania Set",
  "price": 2500,
  "description": "5 Piece Set",
  "quantity": 5,
  "supplier_id": 2
}



#--------------------------------------------------
### Product Update Action
PATCH http://localhost:3000/products/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Lania Set",
  "price": 2500,
  "description": "5 Piece Set",
  "quantity": 5,
  "supplier_id": 2
}



#--------------------------------------------------
### Product Delete

DELETE http://localhost:3000/products/7
Content-Type: application/json
 
###---------------------------------------------

### Users create (signup)

POST http://localhost:3000/users.json
Content-Type: application/json

{

  "name": "JP",
  "email": "jp@test.com",
  "password": "password",
  "password_confirmation": "password"
}


###---------------------------------------------

### Session Create (User login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jp@test.com",
  "password": "password"
}

###---------------------------------------------

### Orders Create

POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}



### Orders Index

GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

###Order Show Action

GET http://localhost:3000/orders/3.json
Authorization: Bearer {{jwt}}





### Carted_Products Index Action

GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}

### Carted_Product Create

POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 3,
  "quantity": 1

}


### Carted Product Destroy
DELETE http://localhost:3000/carted_products/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json