###Index Action

GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjgyODYyOTV9.s3ytpYS0pVtfaKDfCeeeZJQe_S7efz22sXxYY4yKlkk

###Show Action


GET http://localhost:3000/products/3.json


###Create

POST http://localhost:3000/products.json
Content-Type: application/json

{
"name": "",
"price": 500,
"image_url": "test.com",
"description": "this",
"quantity": 3
}


###  Update Action
PATCH http://localhost:3000/products/8
Content-Type: application/json

{
"name": "test",
"price": 5,
"image_url": "https://cdn.shopify.com/s/files/1/0070/8342/5882/products/Rialto_Sofa_Bed_-_Dawson_Moon_-_P02_-_1024x1024_b1a536fb-b170-44f4-8556-71284815f6ca_grande.jpg?v=1621022918",
"description": "this"
}


### Delete

DELETE http://localhost:3000/products/7
Content-Type: application/json
 

### Users create (signup)

POST http://localhost:3000/users.json
Content-Type: application/json

{

  "name": "Mike",
  "email": "mike@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Session Create (User login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mike@test.com",
  "password": "password"
}


### Orders Create

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njg0NDY4NTl9.VSQKG6Mo0cHD6FJg62DrW0HeTLhgeJSZ1CMGPPsQSmM

{
  "product_id": 1,
  "quantity":  10
}


### Orders Index

GET http://localhost:3000/orders.json


###Order Show Action

GET http://localhost:3000/orders/3.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njg0NDY4NTl9.VSQKG6Mo0cHD6FJg62DrW0HeTLhgeJSZ1CMGPPsQSmM
