###Index Action

GET http://localhost:3000/products


###Show Action


GET http://localhost:3000/products/2


###Create

POST http://localhost:3000/products
Content-Type: application/json

{
"name": "test name",
"price": 40,
"image_url": "test.com",
"description": "this is a test"
}


###  Update Action
PATCH http://localhost:3000/products/8
Content-Type: application/json

{
"name": "Sofa Bed",
"price": 800,
"image_url": "https://cdn.shopify.com/s/files/1/0070/8342/5882/products/Rialto_Sofa_Bed_-_Dawson_Moon_-_P02_-_1024x1024_b1a536fb-b170-44f4-8556-71284815f6ca_grande.jpg?v=1621022918",
"description": "this is a nice bed"
}


### Delete

DELETE http://localhost:3000/products/7
Content-Type: application/json
 
